# example
apiVersion: observability.oracle.com/v4
kind: DatabaseObserver
metadata:
  name: obs-sample
  labels:
    app.kubernetes.io/name: observability-exporter
    app.kubernetes.io/instance: obs-sample
    app.kubernetes.io/version: 2.0.2
spec:
  database:
    dbUser:
      key: "username"
      secret: db-secret

    dbPassword:
      key: "password"
      secret: db-secret

    dbConnectionString:
      key: "connection"
      secret: db-secret

  wallet:
    secret: instance-wallet

  inheritLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - app.kubernetes.io/version

  sidecar:
    containers:
      - name: promtail
        image: grafana/promtail
        args:
          - -config.file=/etc/promtail/promtail.yaml
        volumeMounts:
          - name: config
            mountPath: /etc/promtail
          - name: log-volume
            mountPath: /log
    volumes:
      - name: config
        configMap:
          name: promtail-sidecar-config


  deployment:
    image: "container-registry.oracle.com/database/observability-exporter:2.0.2"
    args: [ "--log.level=info" ]
    commands: [ "/oracledb_exporter" ]



  serviceMonitor:
    labels:
      release: prometheus

  metrics:
    configMap:
      - name: "devcm-oradevdb-config"
        key: "config.toml"

  log:
    destination: "/log"
    filename: "alert.log"


  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey

  replicas: 1
