# example
apiVersion: observability.oracle.com/v4
kind: DatabaseObserver
metadata:
  name: obs-sample
  labels:
    app.kubernetes.io/name: observability-exporter
    app.kubernetes.io/instance: obs-sample
    app.kubernetes.io/version: latest
spec:
  database:
    dbUser:
      key: "username"
      secret: db-secret

    dbPassword:
      key: "password"
      secret: db-secret

    dbConnectionString:
      key: "connection"
      secret: db-secret

  wallet:
    secret: instance-wallet

  inheritLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - app.kubernetes.io/version

  sidecar:
    containers: [ ]
    volumes: [ ]

  deployment:
    env:
      TNS_ADMIN: /some/custom/path
      ORACLE_HOME: /some/custom/path
      DB_ROLE: SYSDBA
    image: "container-registry.oracle.com/database/observability-exporter:2.0.2"
    args: [ "--log.level=info" ]
    commands: [ "/oracledb_exporter" ]

    labels:
      environment: dev
    podTemplate:
      labels:
        environment: dev

  service:
    labels:
      environment: dev

  serviceMonitor:
    labels:
      release: prometheus

  metrics:
    configMap:
      - name: "devcm-oradevdb-config"
        key: "config.toml"

  log:
    filename: "alert.log"
    destination: "/log"

    volume:
      persistentVolumeClaim:
        claimName: "my-pvc"

  ociConfig:
    configMap:
      key: config
      name: oci-cred
    privateKey:
      secret: oci-privatekey
    mountPath: "/.oci"

  replicas: 1
