# example
apiVersion: observability.oracle.com/v4
kind: DatabaseObserver
metadata:
  name: obs-sample
spec:
  database:
    dbUser:
      secret: db-secret

    dbPassword:
      secret: db-secret

    dbConnectionString:
      secret: db-secret

    dbWallet:
      secret: instance-wallet

  prometheus:
    serviceMonitor:
      labels:
        release: prometheus
