# example
apiVersion: observability.oracle.com/v4
kind: DatabaseObserver
metadata:
  name: obs-sample
  labels:
    app.kubernetes.io/name: observability-exporter
    app.kubernetes.io/instance: obs-sample
    app.kubernetes.io/version: 2.0.2
spec:
  database:
    dbUser:
      key: "username"
      secret: db-secret

    dbPassword:
      key: "password"
      secret: db-secret

    dbConnectionString:
      key: "connection"
      secret: db-secret

  wallet:
    secret: instance-wallet

  inherit_labels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - app.kubernetes.io/version


  deployment:
    image: "container-registry.oracle.com/database/observability-exporter:1.5.1"
    args: [ "--log.level=info" ]
    commands: [ "/oracledb_exporter" ]

  metrics:
    configMap:
      - name: "devcm-oradevdb-config"
        key: "config.toml"


  serviceMonitor:
    labels:
      release: prometheus