#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
---
# API version of the ShardingDatabase Custom Resource
apiVersion: database.oracle.com/v4

# Resource type being created
kind: ShardingDatabase

# Metadata section to define the resource's name and namespace
metadata:
  name: shardingdatabase-sample                                             # Name of the ShardingDatabase instance
  namespace: shns                                                           # Kubernetes namespace to deploy into

# Specs for the ShardingDatabase instance
spec:

 # Details of the individual shard databases
 shard:
    - name: shard1                                                          # Name of the shard database
      storageSizeInGb: 50                                                   # Size of the Disk Storage allocated to the Shard Database pod
      imagePullPolicy: "Always"                                             # Image Pull Policy for the Database Container Image
      nodeSelector:                                                         # Node Selector the worker node to deploy the Pod. Worker Node with this label will be selected for the Pod.
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvMatchLabels:                                                        # To specify the availability domain where the Persistent Volume will be created. It should be same as the nodeSelector.
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volumebackup.oc1.phx.abyhqljrxtv7tu5swqb3lzc7vpzwbwzdktd2y4k2vjjy2srmgu2w7bqdftjq      # Specify the OCID of the Block Volume Backup which has the Database Gold Image
      shardSpace: sspace1                                                   # Shard Space name for the Shard Database with User Defined Sharding
      shardRegion: primary                                                  # Name of the region for the Shard Database      
    - name: shard2
      storageSizeInGb: 50
      imagePullPolicy: "Always"
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-2"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-2"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volumebackup.oc1.phx.abyhqljrxtv7tu5swqb3lzc7vpzwbwzdktd2y4k2vjjy2srmgu2w7bqdftjq
      shardSpace: sspace2
      shardRegion: primary
    - name: shard3
      storageSizeInGb: 50
      imagePullPolicy: "Always"
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-3"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-3"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volumebackup.oc1.phx.abyhqljrxtv7tu5swqb3lzc7vpzwbwzdktd2y4k2vjjy2srmgu2w7bqdftjq 
      shardSpace: sspace3
      shardRegion: primary

 # Details of the individual shard databases           
 catalog:
    - name: catalog                                                         # Name of the Catalog database
      storageSizeInGb: 50                                                   # Size of the Disk Storage allocated to the Shard Database pod
      imagePullPolicy: "Always"                                             # Image Pull Policy for the Database Container Image
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-1"
      pvAnnotations:
        volume.beta.kubernetes.io/oci-volume-source: ocid1.volumebackup.oc1.phx.abyhqljrxtv7tu5swqb3lzc7vpzwbwzdktd2y4k2vjjy2srmgu2w7bqdftjq    

 # Details of the GSM Pods     
 gsm:
    - name: gsm1                                                            # Name of the Primary Global Service Manager
      imagePullPolicy: "Always"                                             # Image Pull Policy for the GSM Container Image
      storageSizeInGb: 50                                                   # Size of the Disk Storage allocated to the GSM pod
      region: primary                                                       # Name of the Primary region for the Shard Database
      nodeSelector:                                                         # Node Selector the worker node to deploy the Pod. Worker Node with this label will be selected for the Pod.
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-3"
      pvMatchLabels:                                                        # To specify the availability domain where the Persistent Volume will be created. It should be same as the nodeSelector.
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-3"      

    - name: gsm2                                                            # Name of the Standby Global Service Manager
      imagePullPolicy: "Always"                                             # Image Pull Policy for the GSM Container Image
      storageSizeInGb: 50                                                   # Size of the Disk Storage allocated to the GSM pod
      region: standby                                                       # Name of the Standby region for the Shard Database
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-3"
      pvMatchLabels:
        "failure-domain.beta.kubernetes.io/zone": "PHX-AD-3"

 # Kubernetes Storage Class Name
 storageClass: oci

 # Database Container Image to be used for Catalog and Shard Database
 dbImage: container-registry.oracle.com/database/enterprise_ru:19.28.0.0

 # Database Conrainer Image Pull Secret
 dbImagePullSecret: ocr-reg-cred

 # GSM Container Image to be used for GSM Pods
 gsmImage: container-registry.oracle.com/database/gsm_ru:19.28.0.0

 # GSM Conrainer Image Pull Secret
 gsmImagePullSecret: ocr-reg-cred

 # Type of the Sharding. By Default, it is System Sharding unless specified to be USER or NATIVE
 shardingType: USER

 # To specify if Catalog and Shard Databases will be deployed by cloning from the Gold Image
 isClone: True 

 # Whether an External Load Balancer has to be configured for the Catalog, Shard and GSM Pods
 isExternalSvc: False

 # If set to true, the Persistent Volumes will be deleted when the deployment for the Oracle Globally Distributed Database is deleted
 isDeleteOraPvc: True

 # Details of the Database Secret 
 dbSecret:
   name: db-user-pass-rsa
   pwdFileName: pwdfile.enc
   keyFileName: key.pem

 # Details of Services to be created for the Oracle Globally Distributed Database Resource
 gsmService:
   - name: oltp_rw_svc
     role: primary
   - name: oltp_ro_svc
     role: primary
