apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: oke-fsspvc
 namespace: pai
spec:
 storageClassName: oci-fss
 accessModes:
 - ReadWriteMany
 resources:
  requests:
    storage: 100Gi
 volumeName: oke-fsspv
