---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - containers
  - deployments
  - endpoints
  - events
  - namespaces
  - persistentvolumeclaim
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - pods/exec
  - pods/log
  - replicasets
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/status
  - daemonsets/status
  - deployments/status
  - persistentvolumeclaim/status
  - services/status
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
- apiGroups:
  - ''''''
  resources:
  - statefulsets/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - pods
  - replicasets
  - services
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - database.oracle.com
  resources:
  - autonomouscontainerdatabases
  - autonomousdatabases
  - dataguardbrokers
  - dbcssystems
  - events
  - lrests
  - lrpdbs
  - oraclerestarts
  - oraclerestdataservices
  - ordssrvs
  - shardingdatabases
  - singleinstancedatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomouscontainerdatabases/status
  - autonomousdatabasebackups/status
  - autonomousdatabaserestores/status
  - dataguardbrokers/status
  - dbcssystems/status
  - lrests/status
  - lrpdbs/status
  - oraclerestarts/status
  - oraclerestdataservices/status
  - ordssrvs/status
  - shardingdatabases/status
  - singleinstancedatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabasebackups
  - autonomousdatabaserestores
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - autonomousdatabases/status
  verbs:
  - patch
  - update
- apiGroups:
  - database.oracle.com
  resources:
  - dataguardbrokers/finalizers
  - lrests/finalizers
  - oraclerestdataservices/finalizers
  - ordssrvs/finalizers
  - singleinstancedatabases/finalizers
  verbs:
  - update
- apiGroups:
  - database.oracle.com
  resources:
  - dbcssystems/finalizers
  - lrpdbs/finalizers
  - oraclerestarts/finalizers
  - shardingdatabases/finalizers
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.oracle.com
  resources:
  - databaseobservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.oracle.com
  resources:
  - databaseobservers/finalizers
  verbs:
  - update
- apiGroups:
  - observability.oracle.com
  resources:
  - databaseobservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - omlai.oracle.com
  resources:
  - privateais
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - omlai.oracle.com
  resources:
  - privateais/finalizers
  verbs:
  - update
- apiGroups:
  - omlai.oracle.com
  resources:
  - privateais/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
