# example
apiVersion: observability.oracle.com/v1alpha1
kind: DatabaseObserver
metadata:
  name: obs-sample
spec:
  database:
    dbUser:
      secret: db-secret

    dbPassword:
      secret: db-secret

    dbConnectionString:
      secret: db-secret

  wallet:
    secret: instance-wallet


  serviceMonitor:
    labels:
      release: prometheus