# API version of the OracleRestart Custom Resource
apiVersion: database.oracle.com/v4

# Resource type being created
kind: OracleRestart

# Metadata section to define the resource's name and namespace
metadata:
  name: oraclerestart-sample          # Name of the OracleRestart instance
  namespace: orestart                 # Kubernetes namespace to deploy into

spec:
  # Instance details for Oracle Restart
  instDetails:
    name: dbmc1                       # Logical name of the OracleRestart instance
    hostSwLocation: /scratch/orestart/  # Host directory for Oracle GI HOME and Oracle RDBMS HOME

    # Worker nodes where the instance should be scheduled
    workerNode:
      - 10.0.10.108                   # IP address of the target node for deployment
    envVars:
      - name: IGNORE_CRS_PREREQS
        value: "true"
      - name: IGNORE_DB_PREREQS
        value: "true"

  # ASM (Automatic Storage Management) storage configuration
  asmStorageDetails:
    disksBySize:
      - storageSizeInGb: 50          # Logical group size (in GB) for ASM disk group
        diskNames:
          - /dev/oracleoci/oraclevdd  # ASM disk device path 1
          - /dev/oracleoci/oraclevde  # ASM disk device path 2

  # SSH key secret used for remote access and automation
  sshKeySecret:
    name: ssh-key-secret          # Kubernetes secret name
    privKeySecretName: ssh-privkey  # Private key inside secret
    pubKeySecretName: ssh-pubkey    # Public key inside secret

  # Secret containing DB user credentials
  dbSecret:
    name: db-user-pass-pkutl     # Secret name
    keyFileName: key.pem         # Key file name inside secret
    pwdFileName: pwdfile.enc     # Password file name inside secret

  # Image for Oracle Restart container
  image: localhost/oracle/database-rac:19.3.0-slim  
  # image: phx.ocir.io/intsanjaysingh/db-repo/oracle/database-rac:19.3.0-slim  # <-- Replace with your image registry

  # Policy to always pull image (useful during testing or if image might change)
  imagePullPolicy: Always

  # Optional service account for security context permissions
  # serviceAccountName: oraclerestart   # <-- Required for OpenShift; optional for vanilla Kubernetes

  # Service-specific database name and related details
  serviceDetails:
    name: soepdb                     # Name of the Oracle service (pluggable DB)

  # Resource requests and limits for memory and CPU
  resources:
    requests:
      memory: "16Gi"                 # Minimum memory required
      cpu: "2"                       # Minimum CPU required
    limits:
      memory: "16Gi"                 # Max memory allowed
      cpu: "2"                       # Max CPU allowed

  # Kernel-level system control parameters for Oracle
  securityContext:
    sysctls:
      - name: kernel.shmall
        value: "2097152"
      - name: kernel.sem
        value: "250 32000 100 128"
      - name: kernel.shmmax
        value: "8589934592"
      - name: kernel.shmmni
        value: "4096"

  # Configuration parameters for Oracle Grid and Database homes
  configParams:
    gridHome: "/u01/app/19c/grid"                             # Oracle Grid home path
    gridBase: "/u01/app/grid"                                 # Grid base directory
    dbHome: "/u01/app/oracle/product/19c/dbhome_1"            # Oracle DB home path
    dbBase: "/u01/app/oracle"                                 # Oracle base directory
    crsAsmDeviceList: /dev/oracleoci/oraclevdd,/dev/oracleoci/oraclevde  # Comma-separated list of ASM device files
    inventory: "/u01/app/oraInventory"                        # Inventory location
    gridSwZipFile: "grid_home.zip"                            # Grid infrastructure software ZIP
    dbSwZipFile: "db_home.zip"                                # Database software ZIP
    sgaSize: "3G"                                             # Size of the System Global Area
    pgaSize: "1G"                                             # Size of the Program Global Area
    processes: 2000                                           # Oracle process limit
    cpuCount: 4                                               # Number of CPUs to allocate
    dbName: "PORCLCDB"                                        # Oracle database name
    hostSwStageLocation: /scratch/software/stage              # Host location where Oracle software ZIPs are staged