# API version for the custom resource definition
apiVersion: database.oracle.com/v4

# Kind of resource being defined
kind: OracleRestart

# Metadata section includes the name and namespace of the resource
metadata:
  # Name of this OracleRestart resource instance
  name: oraclerestart-sample
  # Kubernetes namespace where this resource resides
  namespace: orestart

# Specification for the OracleRestart resource
spec:
  # Details about the Oracle instance
  instDetails:
    # Name of the Oracle instance
    name: dbmc1
    # Path where Oracle software will be installed on the host
    hostSwLocation: /scratch/orestart/
    # Target port for Oracle Notification Services (ONS)
    onsTargetPort: 30200
    # List of worker node IPs where instance will be deployed
    workerNode:
      - 10.0.10.108
    
    envVars:
      - name: IGNORE_CRS_PREREQS
        value: "true"
      - name: IGNORE_DB_PREREQS
        value: "true"
    # NodePort service configuration
    nodePortSvc:
      - svcType: nodeport  # Type of service (NodePort)
        name: dbmc1         # Name of the NodePort service
    # Port mappings between container and host
    portMappings:
      - port: 1521          # Internal port for Oracle DB
        targetPort: 1521    # Target port inside the container
        protocol: TCP       # Protocol used
        nodePort: 30007     # Exposed NodePort on host

  # ASM (Automatic Storage Management) disk configuration
  asmStorageDetails:
    disksBySize:
      - storageSizeInGb: 50          # Total size of disk group in GB
        diskNames:                   # List of physical disk paths to be used
          - /dev/oracleoci/oraclevdd
          - /dev/oracleoci/oraclevde

  # SSH key secret references used for host access
  sshKeySecret:
    name: ssh-key-secret             # Name of the Kubernetes secret
    privKeySecretName: ssh-privkey   # Private SSH key secret
    pubKeySecretName: ssh-pubkey     # Public SSH key secret

  # Database user credentials secret
  dbSecret:
    name: db-user-pass-pkutl         # Name of secret containing DB credentials
    keyFileName: key.pem             # Key file name inside secret
    pwdFileName: pwdfile.enc         # Password file name inside secret

  # Container image for Oracle Restart
  image: phx.ocir.io/intsanjaysingh/db-repo/oracle/database-rac:19.3.0-slim-0729

  # Policy to always pull the image when starting
  imagePullPolicy: Always

  # Details of the database service
  serviceDetails:
    name: soepdb                     # Name of the database service

  # Kubernetes resource requests and limits
  resources:
    requests:
      memory: "16Gi"                 # Memory requested by container
      cpu: "2"                       # CPUs requested by container
    limits:
      memory: "16Gi"                 # Maximum memory allowed
      cpu: "2"                       # Maximum CPUs allowed

  # OS-level kernel parameters to be set in the container
  securityContext:
    sysctls:
    - name: kernel.shmall
      value: "2097152"              # Shared memory pages
    - name: kernel.sem
      value: "250 32000 100 128"    # Semaphore settings
    - name: kernel.shmmax
      value: "8589934592"           # Max shared memory segment (8GB)
    - name: kernel.shmmni
      value: "4096"                 # Number of shared memory segments

  # Configuration parameters for Oracle software
  configParams:
    gridHome: "/u01/app/19c/grid"                          # Path to Grid Infrastructure home
    gridBase: "/u01/app/grid"                              # Base directory for Grid Infrastructure
    dbHome: "/u01/app/oracle/product/19c/dbhome_1"         # Oracle Database home
    dbBase: "/u01/app/oracle"                              # Oracle Database base directory
    crsAsmDeviceList: /dev/oracleoci/oraclevdd,/dev/oracleoci/oraclevde  # ASM device list
    inventory: "/u01/app/oraInventory"                     # Oracle inventory location
    gridSwZipFile: "grid_home.zip"                         # Grid software zip filename
    dbSwZipFile: "db_home.zip"                             # DB software zip filename
    sgaSize: "3G"                                          # Size of SGA (System Global Area)
    pgaSize: "1G"                                          # Size of PGA (Program Global Area)
    processes: 2000                                        # Maximum number of DB processes
    cpuCount: 4                                            # Number of CPUs to allocate
    dbName: "PORCLCDB"                                     # Name of the Oracle database
    hostSwStageLocation: "/scratch/software/19c/19.3.0/"   # Location to stage installation software
    ruPatchLocation: /scratch/software/19c/19.28/          # Location for Release Update patch